### ISSUE TITLE
Sold Domains should store Actual Rate?

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-cache#73]
Should we store the Actual rate used when a domain was sold? 
When you are actually looking at past transactions makes more sense to see the transaction value at the time than the current conversion?

**Comment by AuHau** [comment]
It makes sense, although it will need some work, because we are not storing historical rates, but only the current one. So we will have to implement support for querying for a specific date (which will be a timestamp of the block). CoinGecko support this so, no problem there ([API doc](https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id__history))

The question is how to do this for historical transactions, eq. for `precache` command. The potential problem here is that we might hit rate-limitation for the API, which might make the `precache` event considerably slower. Especially the more events there will be to process. But I guess this is a solvable problem which we can tackle later on.

From my side. It is doable and make sense, but I would tackle this after the Consensys presentation.

**Comment by jurajpiar** [comment]
can we not just store the rate in the sold table along with the rest of the information at the time of the event?

**Comment by AuHau** [comment]
Yes, that is possible for the new events, but not for the old ones (eq. when `precache` is run).

**Comment by AuHau** [comment]
@julianmrodri do we have a page/usecase where we are displaying "historical rates"? If so this should be I guess tackled otherwise I would close it and left it to point when it will be needed.

**Comment by jurajpiar** [comment]
We do have a sold domains page where, presumably you'd like to see how much you sold your domains for.

**Comment by julianmrodri** [comment]
Closing we will not be tackling this at the moment.
